name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build the project
      run: cargo build --release

    - name: Create release directory
      run: mkdir release

    - name: Move executable to release directory
      run: move target\release\realese.exe release\

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: release\realese.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
